import { Plus } from "lucide-react";
import { useEffect, useState } from "react";
import InputForm from "./InputForm";
import ListCard from "./ListCard";
import { toast } from "react-hot-toast";
import axios from "axios";

export interface ListItemsType {
  _id?: string;
  itemName: string;
  quantity: number;
  price: number;
  completed: boolean;
}

function ListItem() {
  const [modal, setModal] = useState(false);
  const [inputValue, setInputValue] = useState<ListItemsType>({
    itemName: "",
    quantity: 0,
    price: 0,
    completed: false,
  });
  const [listItems, setListItems] = useState<ListItemsType[]>([]);
  const [editId, setEditId] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState("All List");

  // Fetch items from backend
  useEffect(() => {
    const fetchItems = async () => {
      try {
        const token = localStorage.getItem("token");

        const response = await axios.get("http://localhost:3000/api/items", {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        });
        setListItems(response.data); // axios puts response in data
      } catch {
        toast.error("Failed to load list items");
      }
    };

    fetchItems();
  }, []);

  // Counts of: All List, Pending List & Completed List
  const allCount = listItems.length;
  const pendingCount = listItems.filter((item) => !item.completed).length;
  const completedCount = listItems.filter((item) => item.completed).length;

  // Filtered Items:
  const filteredItems = listItems.filter((item) => {
    if (activeTab === "Pending") {
      return !item.completed; // Pending Items
    } else if (activeTab === "Completed") {
      return item.completed; // Completed Items
    } else {
      return item; // All Items
    }
  });

  // Total Cost Calculation:
  // returns items that is not completed and the item that is completed, it will not return that
  const totalCost = listItems
    .filter((item) => !item.completed)
    .reduce((accumulator, item) => {
      const sum = Number(item.quantity) || 0;
      return accumulator + item.price * sum;
    }, 0);

  // Function: handleSubmit -> CREATE / UPDATE
  const handleSubmit = async (items: ListItemsType) => {
    try {
      const token = localStorage.getItem("token");
      // EDIT ITEM
      if (editId) {
        const response = await axios.put(
          `http://localhost:3000/api/items/${editId}`,
          items,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        setListItems((prevItems) => {
          return prevItems.map((item) => {
            // If this index is being edited, replace the item with the updated input value user type at that time; otherwise return the existing item as it is
            // Entire inputs of item will be updated
            return item._id === editId ? response.data.item : item;
          });
        });
        toast.success("Item updated!");
        setEditId(null);
        // ADD ITEM
      } else {
        const response = await axios.post(
          "http://localhost:3000/api/items",
          items,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        setListItems((prevItems) => {
          return [...prevItems, response.data.item];
        });
        toast.success("Item added to your list!");
      }
      // Clear Input Fields
      setInputValue({ itemName: "", quantity: 0, price: 0, completed: false });
      setModal(false);
    } catch {
      toast.error("Failed to add item to your list!");
    }
  };

  // Function: handleComplete
  const handleComplete = async (id: string) => {
    try {
      const token = localStorage.getItem("token");
      const response = await axios.patch(
        `http://localhost:3000/api/items/${id}/toggle`,
        {},
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      setListItems((prevItems) => {
        return prevItems.map((item) =>
          // Iterate through listItems to find the specific item to update:
          // - Each item has an automatic '_id' generated by the database.
          // - If item._id matches the clicked ID, replace it with the updated data from the server.
          // - Otherwise, return the item as-is to keep the array unchanged.
          // - response.data.item === updated item with status changed to completed
          item._id === id ? response.data.item : item
        );
      });
    } catch {
      toast.error("Failed to update item!");
    }
  };

  // Function: handleEdit
  const handleEdit = (id: string) => {
    const itemToEdit = listItems.find((item) => item._id === id);
    if (itemToEdit) {
      setInputValue(itemToEdit);
    }
    setEditId(id); // Tracks which index to edit
    setModal(true);
  };

  // Function: handleDelete
  const handleDelete = async (id: string) => {
    try {
      const token = localStorage.getItem("token");

      await axios.delete(`http://localhost:3000/api/items/${id}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });
      setListItems((prevItems) => {
        return prevItems.filter((item) => {
          // return item only if its index is not equal to index to delete.
          return item._id !== id;
        });
      });
      toast.success("Item removed!");
    } catch {
      toast.error("Failed to remove item!");
    }
  };

  return (
    <>
      {/* Form Modal */}
      {modal && (
        <InputForm
          setModal={setModal}
          onSubmit={handleSubmit}
          inputValue={inputValue}
          setInputValue={setInputValue}
          editId={editId}
          setEditId={setEditId}
        />
      )}
      <div className="space-y-5 ">
        {/* HEADER */}
        <div className="flex justify-between items-center mt-6 p-6 rounded-lg shadow-sm bg-white border-gray-300">
          <p className="text-xl font-bold"> Total Cost: Rs {totalCost} </p>
          <button
            onClick={() => setModal(!modal)}
            className="flex justify-center items-center gap-2 py-2 px-4 text-sm rounded-lg bg-blue-600 hover:bg-blue-700 text-white cursor-pointer "
          >
            <Plus /> Add New List
          </button>
        </div>

        <div className="space-y-5 p-6 bg-white rounded-lg shadow-sm ">
          {/* TABS */}
          <div className="space-x-2">
            <button
              onClick={() => setActiveTab("All List")}
              className={`py-2 px-4 text-sm rounded-lg border hover:bg-background-page transition-colors cursor-pointer ${
                activeTab == "All List" &&
                "bg-blue-600 text-white hover:bg-blue-700 transition-colors"
              }`}
            >
              All List ({allCount})
            </button>
            <button
              onClick={() => setActiveTab("Pending")}
              className={`py-2 px-4 text-sm rounded-lg border hover:bg-background-page transition-colors cursor-pointer ${
                activeTab == "Pending" &&
                "bg-blue-600 text-white hover:bg-blue-700 transition-colors"
              }`}
            >
              Pending ({pendingCount})
            </button>
            <button
              onClick={() => setActiveTab("Completed")}
              className={`py-2 px-4 text-sm rounded-lg border hover:bg-background-page transition-colors cursor-pointer ${
                activeTab == "Completed" &&
                "bg-blue-600 text-white hover:bg-blue-700 transition-colors"
              }`}
            >
              Completed ({completedCount})
            </button>
          </div>

          {/* LISTS */}
          <div className="min-h-[calc(100vh-350px)]  ">
            {filteredItems.length === 0 ? (
              <div className="min-h-[calc(100vh-350px)] text-lg text-gray-400 flex justify-center items-center ">
                List is currenty empty
              </div>
            ) : (
              <div className="space-y-5">
                {filteredItems.map((item) => {
                  return (
                    <ListCard
                      key={item._id}
                      item={item}
                      handleComplete={handleComplete}
                      handleEdit={handleEdit}
                      handleDelete={handleDelete}
                    />
                  );
                })}
              </div>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

export default ListItem;
